name: CodeQL

on:
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - 'tests/**'
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'tests/**'
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  code_ql:
    runs-on: ubuntu-latest
    name: CodeQL
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
